// prisma/seeds/personnel-types.seed.ts
import { PrismaClient } from "@prisma/client";

type PersonnelHierarchy = "DEVELOPER" | "DIRECTOR" | "GROUP_HEAD" | "STAFF" | "STUDENT";

export async function seedPersonnelTypes(prisma: PrismaClient, hospitals: any[], devUser: any) {
  console.log("🎯 Creating Personnel Types (Master Data)...");

  const personnelTypesTemplate = [
    {
      typeCode: "DEV",
      typeName: "นักพัฒนา",
      typeNameEn: "Developer", 
      hierarchy: "DEVELOPER" as PersonnelHierarchy,
      levelOrder: 1,
      canManageHospitals: true,
      canManageWarehouses: true,
      canManageDepartments: true,
      canManagePersonnel: true,
      canManageDrugs: true,
      canManageMasterData: true,
      canViewReports: true,
      canApproveUsers: true,
      description: "ผู้พัฒนาระบบ มีสิทธิ์สูงสุดในการจัดการข้อมูลทั้งหมด",
      responsibilities: ["พัฒนาระบบ", "ดูแลระบบ", "จัดการข้อมูลหลัก", "แก้ไขปัญหาเทคนิค"],
      isSystemDefault: true,
    },
    {
      typeCode: "DIR",
      typeName: "ผู้อำนวยการ",
      typeNameEn: "Director",
      hierarchy: "DIRECTOR" as PersonnelHierarchy, 
      levelOrder: 10,
      canManageHospitals: false,
      canManageWarehouses: true,
      canManageDepartments: true,
      canManagePersonnel: true,
      canManageDrugs: true,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: true,
      description: "ผู้อำนวยการโรงพยาบาล บริหารจัดการระดับสูง",
      responsibilities: ["บริหารโรงพยาบาล", "อนุมัติงบประมาณ", "กำหนดนโยบาย", "ควบคุมคุณภาพ"],
      maxSubordinates: 50,
      defaultDepartmentType: "ADMINISTRATION",
    },
    {
      typeCode: "ASST_DIR",
      typeName: "รองผู้อำนวยการ",
      typeNameEn: "Assistant Director",
      hierarchy: "DIRECTOR" as PersonnelHierarchy,
      levelOrder: 15,
      canManageHospitals: false,
      canManageWarehouses: true,
      canManageDepartments: true,
      canManagePersonnel: false,
      canManageDrugs: true,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: true,
      description: "รองผู้อำนวยการ ช่วยบริหารงานระดับสูง",
      responsibilities: ["ช่วยบริหารโรงพยาบาล", "ควบคุมการดำเนินงาน", "กำกับแผนก"],
      maxSubordinates: 30,
    },
    {
      typeCode: "CHIEF_PHARM",
      typeName: "หัวหน้าเภสัชกรรม",
      typeNameEn: "Chief Pharmacist",
      hierarchy: "GROUP_HEAD" as PersonnelHierarchy,
      levelOrder: 20,
      canManageHospitals: false,
      canManageWarehouses: true,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: true,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "หัวหน้าแผนกเภสัชกรรม ดูแลงานยาและเวชภัณฑ์",
      responsibilities: ["จัดการระบบยา", "ควบคุมคุณภาพยา", "อนุมัติการเบิกจ่าย", "บริหารคลังยา"],
      maxSubordinates: 15,
      defaultDepartmentType: "PHARMACY",
    },
    {
      typeCode: "CHIEF_NURSE",
      typeName: "หัวหน้าพยาบาล",
      typeNameEn: "Chief Nurse",
      hierarchy: "GROUP_HEAD" as PersonnelHierarchy,
      levelOrder: 20,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "หัวหน้าฝ่ายการพยาบาล ดูแลงานพยาบาล",
      responsibilities: ["บริหารงานพยาบาล", "ควบคุมคุณภาพการดูแล", "พัฒนาบุคลากร"],
      maxSubordinates: 20,
      defaultDepartmentType: "NURSING",
    },
    {
      typeCode: "DEPT_HEAD",
      typeName: "หัวหน้าแผนก",
      typeNameEn: "Department Head",
      hierarchy: "GROUP_HEAD" as PersonnelHierarchy,
      levelOrder: 25,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "หัวหน้าแผนกต่างๆ ดูแลงานเฉพาะด้าน",
      responsibilities: ["บริหารแผนก", "ควบคุมงานประจำ", "รายงานผลการดำเนินงาน"],
      maxSubordinates: 12,
    },
    {
      typeCode: "SR_PHARM",
      typeName: "เภสัชกรชำนาญการ",
      typeNameEn: "Senior Pharmacist",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 30,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: true,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "เภสัชกรชำนาญการ มีประสบการณ์สูง",
      responsibilities: ["จ่ายยาผู้ป่วยใน", "ให้คำปรึกษายา", "ตรวจสอบคำสั่งยา", "ควบคุมยาพิเศษ"],
      maxSubordinates: 5,
      defaultDepartmentType: "PHARMACY",
    },
    {
      typeCode: "PHARM",
      typeName: "เภสัชกร",
      typeNameEn: "Pharmacist",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 35,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "เภสัชกรปฏิบัติการ จ่ายยาและให้คำปรึกษา",
      responsibilities: ["จ่ายยาผู้ป่วยนอก", "ให้คำปรึกษายา", "บันทึกข้อมูลยา"],
      defaultDepartmentType: "PHARMACY",
    },
    {
      typeCode: "SR_NURSE",
      typeName: "พยาบาลวิชาชีพชำนาญการ",
      typeNameEn: "Senior Nurse",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 30,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "พยาบาลวิชาชีพชำนาญการ ดูแลผู้ป่วยและควบคุมงาน",
      responsibilities: ["ดูแลผู้ป่วย", "เบิกยาประจำแผนก", "ควบคุมงานพยาบาล"],
      maxSubordinates: 8,
    },
    {
      typeCode: "NURSE",
      typeName: "พยาบาลวิชาชีพ",
      typeNameEn: "Registered Nurse",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 35,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: false,
      canApproveUsers: false,
      description: "พยาบาลวิชาชีพ ดูแลผู้ป่วยโดยตรง",
      responsibilities: ["ดูแลผู้ป่วย", "ให้ยาตามแพทย์สั่ง", "บันทึกสัญญาณชีพ"],
    },
    {
      typeCode: "NURSE_ASS",
      typeName: "ผู้ช่วยพยาบาล",
      typeNameEn: "Nursing Assistant",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 40,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: false,
      canApproveUsers: false,
      description: "ผู้ช่วยพยาบาล ช่วยงานการพยาบาล",
      responsibilities: ["ช่วยดูแลผู้ป่วย", "ช่วยงานประจำ", "ติดต่อประสานงาน"],
    },
    {
      typeCode: "PHARM_TECH",
      typeName: "ผู้ช่วยเภสัชกร",
      typeNameEn: "Pharmacy Technician",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 40,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: false,
      canApproveUsers: false,
      description: "ผู้ช่วยเภสัชกร ช่วยงานเภสัชกรรม",
      responsibilities: ["ช่วยจ่ายยา", "จัดเก็บยา", "ช่วยงานคลัง"],
      defaultDepartmentType: "PHARMACY",
    },
    {
      typeCode: "ADMIN",
      typeName: "เจ้าหน้าที่บริหาร",
      typeNameEn: "Administrative Staff",
      hierarchy: "STAFF" as PersonnelHierarchy,
      levelOrder: 35,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: true,
      canApproveUsers: false,
      description: "เจ้าหน้าที่บริหารงานทั่วไป",
      responsibilities: ["งานสารบรรณ", "ประสานงาน", "จัดการข้อมูล"],
      defaultDepartmentType: "ADMINISTRATION",
    },
    {
      typeCode: "INTERN_PHARM",
      typeName: "นักศึกษาเภสัชศาสตร์",
      typeNameEn: "Pharmacy Intern",
      hierarchy: "STUDENT" as PersonnelHierarchy,
      levelOrder: 50,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: false,
      canApproveUsers: false,
      description: "นักศึกษาเภสัชศาสตร์ฝึกงาน",
      responsibilities: ["เรียนรู้การจ่ายยา", "ช่วยงานเภสัชกร", "ศึกษาระบบงาน"],
      defaultDepartmentType: "PHARMACY",
    },
    {
      typeCode: "INTERN_NURSE",
      typeName: "นักศึกษาพยาบาล",
      typeNameEn: "Nursing Student",
      hierarchy: "STUDENT" as PersonnelHierarchy,
      levelOrder: 50,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: false,
      canApproveUsers: false,
      description: "นักศึกษาพยาบาลฝึกงาน",
      responsibilities: ["เรียนรู้การดูแลผู้ป่วย", "ช่วยงานพยาบาล", "ศึกษาการปฏิบัติงาน"],
    },
    {
      typeCode: "TRAINEE",
      typeName: "พนักงานฝึกหัด",
      typeNameEn: "Trainee",
      hierarchy: "STUDENT" as PersonnelHierarchy,
      levelOrder: 55,
      canManageHospitals: false,
      canManageWarehouses: false,
      canManageDepartments: false,
      canManagePersonnel: false,
      canManageDrugs: false,
      canManageMasterData: false,
      canViewReports: false,
      canApproveUsers: false,
      description: "พนักงานฝึกหัดใหม่",
      responsibilities: ["เรียนรู้งานใหม่", "ช่วยงานพื้นฐาน", "ปฏิบัติตามคำแนะนำ"],
    },
  ];

  // สร้าง Personnel Types สำหรับทุกโรงพยาบาล
  const allPersonnelTypes: Record<string, any[]> = {};
  
  for (const hospital of hospitals) {
    console.log(`🏥 Creating Personnel Types for ${hospital.name}...`);
    
    const hospitalPersonnelTypes: any[] = [];
    
    for (const template of personnelTypesTemplate) {
      const created = await prisma.personnelType.upsert({
        where: { 
          hospitalId_typeCode: {
            hospitalId: hospital.id,
            typeCode: template.typeCode
          }
        },
        update: {},
        create: {
          ...template,
          hospitalId: hospital.id,
          createdBy: devUser.id
        }
      });
      hospitalPersonnelTypes.push(created);
      console.log(`  ✅ ${template.typeName} (${template.typeCode})`);
    }
    
    allPersonnelTypes[hospital.id] = hospitalPersonnelTypes;
  }

  console.log(`✅ Successfully created ${personnelTypesTemplate.length} personnel types for ${hospitals.length} hospitals`);
  return allPersonnelTypes;
}