// prisma/seed.ts - Auto-generated Modular Seed File
// Generated by scripts/merge-seeds.js v2.5 - Final Warehouse Integration
// Do not edit manually - modify individual seed files instead

import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../lib/password-utils";

import { seedHospitals } from "./seeds/hospitals.seed";
import { seedPersonnelTypes } from "./seeds/personnel-types.seed";
import { seedDepartments } from "./seeds/departments.seed";
import { seedWarehouses } from "./seeds/warehouses.seed";
import { seedUsers } from "./seeds/users.seed";
import { seedMasterData } from "./seeds/master-data.seed";
import { seedBulkRealDrugs } from "./seeds/robust-bulk-drugs.seed";
import { seedDemoData } from "./seeds/demo-data.seed";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting Enhanced Hospital Pharmacy Stock Management System Seed...");
  console.log("🎯 Using Modular Seed Architecture with Neon + Prisma");
  console.log("⚡ Enhanced with Bulk Drug Processing Support v2.5");
  console.log("🏪 Full warehouse management enabled");

  try {
    // ================================
    // PHASE 1: FOUNDATION
    // ================================
    console.log("\n🏗️  PHASE 1: Foundation Setup");
    
    // 1. Create hospitals first
    const hospitals = await seedHospitals(prisma, null);
    console.log(`✅ Created ${hospitals.length} hospitals`);

    // 2. Create system developer with first hospital
    console.log("👤 Creating system developer user...");
    const hashedDevPassword = await hashPassword("dev123");
    const devUser = await prisma.user.upsert({
      where: { email: "dev@system.local" },
      update: {},
      create: {
        email: "dev@system.local",
        username: "developer",
        name: "System Developer",
        firstName: "System",
        lastName: "Developer", 
        phoneNumber: "0800000000",
        employeeId: "DEV001",
        position: "System Developer",
        role: "DEVELOPER",
        status: "ACTIVE",
        hospitalId: hospitals[0].id,
        personnelTypeId: undefined,
        isProfileComplete: true,
        emailVerified: true,
        password: hashedDevPassword,
      },
    });
    console.log("✅ System developer created");

    // ================================
    // PHASE 2: ORGANIZATIONAL STRUCTURE
    // ================================
    console.log("\n🏢 PHASE 2: Organizational Structure");
    
    // 3. Create personnel types for all hospitals
    const personnelTypes = await seedPersonnelTypes(prisma, hospitals, devUser);
    console.log(`✅ Created personnel types for all hospitals`);

    // Update dev user with developer personnel type
    const devPersonnelType = personnelTypes[hospitals[0].id].find(pt => pt.typeCode === "DEV");
    await prisma.user.update({
      where: { id: devUser.id },
      data: { personnelTypeId: devPersonnelType?.id }
    });

    // 4. Create departments for all hospitals
    const departments = await seedDepartments(prisma, hospitals);
    console.log(`✅ Created departments for all hospitals`);

    // ================================
    // PHASE 2.5: WAREHOUSE INFRASTRUCTURE
    // ================================
    console.log("\n🏪 PHASE 2.5: Warehouse Infrastructure");
    
    
    // 5. Create comprehensive warehouses for all hospitals
    const warehouses = await seedWarehouses(prisma, hospitals);
    console.log(`✅ Created comprehensive warehouses for all hospitals`);
    

    // ================================
    // PHASE 3: PERSONNEL
    // ================================
    console.log("\n👥 PHASE 3: Personnel Management");
    
    // 6. Create diverse users with proper role assignments
    const users = await seedUsers(prisma, hospitals, departments, personnelTypes);
    console.log(`✅ Created ${users.length} users with role assignments`);

    // ================================
    // PHASE 4: MASTER DATA
    // ================================
    console.log("\n💊 PHASE 4: Master Data Setup");
    
    // 7. Create master data (drug forms, groups, types, etc.)
    const masterData = await seedMasterData(prisma, hospitals, devUser);
    console.log(`✅ Created master data for all hospitals`);

    // ================================
    // PHASE 5: DRUG DATA PROCESSING
    // ================================
    console.log("\n💊 PHASE 5: Drug Data Processing");
    console.log("⚡ Using enhanced bulk processing for 400+ drug dataset");
    
    // Execute drug seeding with warehouse support
    console.log(`🔄 Starting seedBulkRealDrugs function...`);
    
    const drugResult = await seedBulkRealDrugs(prisma, hospitals, masterData, warehouses);
    
    // Enhanced result handling
    if (drugResult && typeof drugResult === 'object') {
      // Handle bulk drug processing results
      if ('totalProcessed' in drugResult && 'totalValue' in drugResult) {
        console.log(`✅ Bulk drug processing completed successfully`);
        console.log(`📊 Total drugs processed: ${drugResult.totalProcessed || 0}`);
        console.log(`💰 Total inventory value: ${(drugResult.totalValue || 0).toLocaleString()} บาท`);
        
        if (drugResult.warehouseUsed) {
          console.log(`🏪 Primary warehouse: ${drugResult.warehouseUsed}`);
        }
        
        if (drugResult.categoriesCount) {
          console.log(`📋 Drug Categories Distribution:`);
          Object.entries(drugResult.categoriesCount).forEach(([category, count]) => {
            console.log(`   - ${category}: ${count} drugs`);
          });
        }
      } else if (Array.isArray(drugResult)) {
        // Handle regular drug processing results (array)
        console.log(`✅ Regular drug processing completed`);
        console.log(`📊 Total drugs created: ${drugResult.length}`);
      } else {
        console.log(`✅ Drug processing completed with custom result format`);
      }
    } else {
      console.log(`⚠️  Drug processing completed but no valid result returned`);
    }

    // ================================
    // PHASE 6: DEMO DATA (Optional)
    // ================================
    console.log("\n🎮 PHASE 6: Demo Data (Optional)");
    
    if (process.env.SEED_DEMO_DATA === "true") {
      const demoData = await seedDemoData(prisma, hospitals, users, masterData);
      console.log(`✅ Created demo data for testing`);
    } else {
      console.log("⏭️  Skipping demo data (set SEED_DEMO_DATA=true to include)");
    }

    // ================================
    // COMPLETION SUMMARY
    // ================================
    console.log("\n🎉 Enhanced Hospital Pharmacy Seed Completed Successfully!");
    console.log("\n📊 Final Summary:");
    console.log(`🏥 Hospitals: ${hospitals.length}`);
    console.log(`👥 Personnel Types: ${Object.values(personnelTypes).flat().length}`);
    console.log(`🏢 Departments: ${Object.values(departments).flat().length}`);
    console.log(`🏪 Warehouses: ${Object.values(warehouses).flat().length}`);
    console.log(`👤 Users: ${users.length + 1} (including dev user)`);
    console.log(`💊 Master Data Categories: ${Object.keys(masterData).length}`);
    
    // Enhanced drug statistics
    if (drugResult && typeof drugResult === 'object' && 'totalProcessed' in drugResult) {
      console.log(`🏥 Bulk Drugs Processed: ${drugResult.totalProcessed || 0}`);
      console.log(`💰 Total Drug Inventory Value: ${(drugResult.totalValue || 0).toLocaleString()} บาท`);
    } else if (Array.isArray(drugResult)) {
      console.log(`🏥 Regular Drugs Created: ${drugResult.length}`);
    }
    
    console.log("\n🔑 System Access Credentials:");
    console.log("🔧 DEVELOPER: dev@system.local / dev123");
    console.log("👨‍💼 DIRECTORS: director@[hospital].go.th / director123");
    console.log("⚕️  PHARMACY: pharm@[hospital].go.th / pharm123");
    console.log("👩‍⚕️ NURSING: nurse@[hospital].go.th / nurse123");
    
    console.log("\n📝 Next Steps:");
    console.log("1. Run: pnpm dev");
    console.log("2. Login as dev@system.local / dev123");
    console.log("3. Test multi-tenant isolation");
    console.log("4. Verify role-based permissions");
    console.log("5. Check drug inventory and stock management");
    console.log("6. Verify 400+ drug bulk processing performance");
    console.log("7. Test stock card creation and batch management");
    console.log("8. Verify warehouse management functionality");

  } catch (error) {
    console.error("❌ Seed error:", error);
    console.error("❌ Error details:", error.message);
    if (error.stack) {
      console.error("❌ Error stack:", error.stack);
    }
    throw error;
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log("\n✅ Database connection closed successfully");
    console.log("🎉 Hospital Pharmacy Seed Process Completed!");
  })
  .catch(async (e) => {
    console.error("❌ Fatal seed error:", e);
    await prisma.$disconnect();
    process.exit(1);
  });

export { prisma };